### ISSUE TITLE
Moment.js.2.14.1.nupkg File contains corrupted data

### ISSUE THREAD

**Issue by vascofernandes** [moment/moment#3285]
Hi,

After installing the new release yesterday, I can no longer install/update any other package.
I get this error in the package manager console.

Unable to read package from path 'Moment.js.2.14.1\Moment.js.2.14.1.nupkg'.
File contains corrupted data.

I am using VS2015, nuget 3.5.0.1448

Regards

**Comment by ichernev** [comment]
@corydeppen hey, I released 2.14.1 from a mac, using nuget@3.4.3 and mono@4.4.0.182. Can you have a look, because I did experience trouble publishing the nuget from the website with some issue about dates in the future, but I did managed to push with the CLI (grunt package).

**Comment by vascofernandes** [comment]
After extraction the content with 7zip, I noticed a difference:

2.13.0
  - Content
        - Scripts
           - moment.js, etc

2.14.1
 - Content%5CScripts
     - moment.js , etc

**Comment by vascofernandes** [comment]
I just packaged it myself and the file structure looks good.
[Moment.js.2.14.1.nupkg.zip](https://github.com/moment/moment/files/347410/Moment.js.2.14.1.nupkg.zip)

**Comment by vascofernandes** [comment]
I guess there should be a 2.14.2 as soon as possible otherwise this problem can affect a lot of people.

Nuget in VS2015 simply does not install/update any packages because this one is corrupted.

So there is really to manual solution:
1 -
in the folder \packages\Moment.js.2.14.1 replace the .nupkg with the new one.

2-
 edit packages.config 
from <package id="Moment.js" version="2.14.1" targetFramework="net45" />
to <package id="Moment.js" version="2.13.0" targetFramework="net45" />
and wait for a new release.

**Comment by corydeppen** [comment]
@vascofernandes Are you using nuget.exe 3.4.4?

**Comment by vascofernandes** [comment]
yes, I did create the new nupkg with nuget.exe 3.4.4.

Regards

**Comment by corydeppen** [comment]
@ichernev Can you try updating nuget.exe to 3.4.4 and see if that resolves the issue?

**Comment by ichernev** [comment]
I pushed 2.14.2, I packaged on my own after deflating, and fixing the dates. @vascofernandes @corydeppen can you give it a try?

**Comment by ichernev** [comment]
I was using 3.2.0.10516 -- that came with grunt-nuget. And the Mac nuget had the right version but apparently can't create a zip file properly.

**Comment by vascofernandes** [comment]
Hi

2.14.2 is still not packaged correctly.

Just compare the contents of 2.13.0 and 2.14.2 and you'll see the the `Content `folder is missing.


Regards

**Comment by corydeppen** [comment]
I just created a package locally using nuget.exe 3.4.4-rtm-final and the `Content` folder appears as I'd expect. I did run into the `File contains corrupted data` message as originally reported, but I was able to get around it by deleting the `Moment.js.2.14.1` folder in the `packages` folder, uninstalling moment, then installing the version I just created.

I don't mind pushing a new version manually, but I'm concerned about bumping the version because it will a) be further out of sync with the other package managers, and b) require the next release to have knowledge of this out of sync version number. Bumping it follows semver, so I guess the next release may need to take this into account.

Please let me know if you'd like me to push a new release.

**Comment by ichernev** [comment]
@corrydeppen -- you can use grunt bump_version:2.14.3, then grunt release, and use that to build/deploy version 2.14.2 only for nuget.

**Comment by corydeppen** [comment]
@ichernev Following `grunt release` it looks like `grunt nuget-publish` should be called to push to NuGet - correct?

**Comment by ichernev** [comment]
@corydeppen well, this uses some obscure NuGet.exe that is shipped with grunt-nuget, so I wouldn't count on it too much, or at least check if the version is ok. My linux box used to work but now it doesn't, so it might be caused by a bad version there.

Other than that -- yes. You can do `grunt nugetpack`, and verify that the produced package is good. Then `grunt nugetpush`.

**Comment by corydeppen** [comment]
2.14.3 has been pushed. I was able to install it into a project without an issue.

Turns out the `nugetpush` task was failing using the current nuget.exe (3.4.4). I discovered there's a new mandatory `Source` [option][1] for the `push` command. I'm planning to log an issue in the grunt-nuget repository asking for nuget.exe to be updated as well as adding a way to pass an argument for `Source`.

[1]: https://docs.nuget.org/consume/command-line-reference#push-command-options

**Comment by ichernev** [comment]
@corydeppen thank you so much!

Now I figured out what happened with 2.14.2 -- I tried to zip it manually but evidently the first argument to zip is the target file, which happened to be Content, and it was not included in the zip itself. I did figure out the -Source argument, at least with the new nuget on my mac. On the linux box I was stuck with some old nuget, which was still producing dates in the future, so I tried to fix it with the manual zip.

**Comment by vascofernandes** [comment]
2.14.3 seems to be working Ok for now..

**Comment by vascofernandes** [comment]
I think this can now be closed. 2.14.3 works Ok.

Regards

**Comment by maggiepint** [comment]
Closing since everybody seems happy with 2.14.3. Thanks Iskren and Cory.
