### ISSUE TITLE
Can't work with interface Moment - it's not exported

### ISSUE THREAD

**Issue by nealeu** [moment/moment#4877]
Using Typescript 3.0.3 and 3.1.3.

When using Moment in other code, we need to be able to pass a moment instance around in a type safe manner.

With the older DefinitelyTyped typings, this worked, but under the included ones in the current release, it doesn't.

```
    import moment = require("moment");
    import {Moment, utc} from "moment";

    public static fromMoment(moment: Moment) {
       // do something with moment in a type safe manner
    }
```

The issue in the typings is simply that 

    interface Moment extends Object {

should read

    export interface Moment extends Object {

Hand editing the included moment.d.ts to make this change fixes the problem.

**Comment by marwahaha** [comment]
Game, as long as we're TS 1.x compatible.

**Comment by akkivarma10** [comment]
Hii, Can I fix this.

**Comment by akkivarma10** [comment]
Submitted PR for this fix #4984

**Comment by djcsdy** [comment]
This is fixed as of moment 2.22.2 (and was probably fixed in a much earlier version).

**Comment by nealeu** [comment]
Closing it's fixed.

**Comment by SouhaibBenFarhat** [comment]
Still not working for me, Using typescript 3.8.3 and moment 2.25.3
`import { Moment } from 'moment';` is raising a not found exception <br>`ESLint: Moment not found in 'moment'(import/named)`

@djcsdy you said it's fixed for newer versions but seems like Moment interface is not exported. 
any fixes for this ? 
Thanks.
