### ISSUE TITLE
Re-open #4803: moment().format() incorrect on older browsers

### ISSUE THREAD

**Issue by Unsfer** [moment/moment#4972]
re-open #4803
Tried on the latest (2.24.0) version, still the same result

```js
var date = "1983-04-01";
var ruDate = moment(date, 'YYYY-MM-DD').format('DD.MM.YYYY');
alert(date + " - " + ruDate);
// Output: "1983-04-01 - 31.03.1983"
```

**Comment by ashsearle** [comment]
@Unsfer What browser(s) are you testing in these days?

If these issues are due to bugs in the browse's implementation of `Date`, it won't be resolved in moment 2.x (see conversation in [issue 4469](https://github.com/moment/moment/issues/4469#issuecomment-400944434))

**Comment by Unsfer** [comment]
Running on Chromium 35 and Firefox 45.9.0
And sadly our env tied on old browsers

**Comment by Unsfer** [comment]
@marwahaha Is it just abandoned?

Tested on last available version, still the same result

https://jsfiddle.net/jv9tzmxr/

```js
var date = "1983-04-01";
var ruDate = moment(date, "YYYY-MM-DD").format("DD.MM.YYYY");
alert("Moment version: " + moment.version + ". \nTest: " + date + " - " + ruDate);
// Output:
// Moment version: 2.25.3. 
// Test: 1983-04-01 - 31.03.1983
```

**Comment by marwahaha** [comment]
I cannot reproduce this:
![image](https://user-images.githubusercontent.com/2541209/81749973-80b05600-9461-11ea-87c1-cda075409844.png)

What time zone or locale are you in?

**Comment by Unsfer** [comment]
The bug only reproduced on browsers mentioned above.

Locale/timezone: ru +0400

The reason probably https://github.com/moment/moment/issues/4803#issuecomment-428934967

**Comment by marwahaha** [comment]
As ashsearle mentioned, if they are related to browser implementation of Date, they cannot be fixed by Moment 2.x

Sorry you are experiencing this issue.
https://momentjs.com/docs/#/-project-status/
